services:
  brainforces:
    build: .
    volumes:
      - static_volume:/brainforces/static
      - media_volume:/brainforces/media
    command: >
      sh -c "cd brainforces && python3 manage.py migrate && gunicorn --bind 0.0.0.0:8000 brainforces.wsgi"
    ports:
      - 8000:8000
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - database
      - redis
      # - rabbitmq
      - elastic
  
  nginx:
    image: nginx:1.23.4-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/brainforces/static
      - media_volume:/brainforces/media
    depends_on:
      - brainforces
    ports:
      - "80:80"

  database:
    image: postgres:15.2-alpine
    restart: always
    container_name: db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
  
  redis:
    image: redis:7.0-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    restart: always
    environment:
      - "discovery.type=single-node"
  
  # rabbitmq:
  #   image: rabbitmq:3.12-alpine
  #   hostname: rabbitmq
  #   restart: always
  #   ports:
  #     - 5672:5672

volumes:
  static_volume:
  media_volume: