# Generated by Django 3.2.16 on 2023-04-12 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_rename_status_organizationtouser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationtouser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Участник'), (2, 'Админ'), (3, 'Создатель'), (4, 'Приглашен')], default=1, help_text='Роль пользователя в организации', verbose_name='роль'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationtouser',
            unique_together={('user', 'organization')},
        ),
    ]
