# Generated by Django 3.2.16 on 2023-04-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organizationpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationpost',
            options={'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
