# Generated by Django 3.2.16 on 2023-04-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_organizationpost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_private',
            field=models.BooleanField(default=True, help_text='приватная организация или нет', verbose_name='приватная'),
        ),
    ]
