# Generated by Django 3.2.16 on 2023-04-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_organization_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='is_private',
            field=models.BooleanField(default=False, help_text='приватная организация или нет', verbose_name='приватная'),
        ),
    ]
