# Generated by Django 3.2.16 on 2023-04-13 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0007_alter_organization_is_private'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organizationpost',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Приватная организация или нет', verbose_name='приватная'),
        ),
        migrations.CreateModel(
            name='CommentToOrganizationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст комментария', verbose_name='текст')),
                ('post', models.ForeignKey(help_text='пост, к которому оставлен комментарий', on_delete=django.db.models.deletion.CASCADE, to='organization.organizationpost', verbose_name='пост')),
                ('user', models.ForeignKey(help_text='Пользователь, котрый оставил комментарий', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
    ]
