# Generated by Django 3.2.16 on 2023-04-13 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20230414_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationpost',
            name='posted_by',
            field=models.ForeignKey(help_text='Организация, написавшая пост', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='organization.organization', verbose_name='организация'),
        ),
    ]
