# Generated by Django 3.2.16 on 2023-05-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_organizationpost_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=False, help_text='активная организация или нет', verbose_name='активная'),
        ),
    ]
