# Generated by Django 3.2.16 on 2023-06-03 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0013_organization_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationpost',
            name='users_liked',
            field=models.ManyToManyField(help_text='пользователи, поставившие лайк', related_name='posts_liked', to=settings.AUTH_USER_MODEL, verbose_name='лайки'),
        ),
    ]
