# Generated by Django 3.2.16 on 2023-06-05 11:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0015_auto_20230603_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationpostlike',
            options={'verbose_name': 'лайк к посту', 'verbose_name_plural': 'лайки к постам'},
        ),
        migrations.AlterUniqueTogether(
            name='organizationpostlike',
            unique_together={('post', 'user')},
        ),
    ]
