# Generated by Django 3.2.16 on 2023-07-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_auto_20230705_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttoorganizationpost',
            name='text',
            field=models.TextField(help_text='Текст комментария', max_length=200, verbose_name='текст'),
        ),
    ]
