# Generated by Django 3.2.16 on 2023-07-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_alter_commenttoorganizationpost_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationpost',
            name='name',
            field=models.CharField(help_text='Название объявления', max_length=75, verbose_name='название'),
        ),
    ]
