# Generated by Django 3.2.16 on 2023-04-05 15:55

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'профиль', 'verbose_name_plural': 'профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, help_text='Аватарка пользователя', null=True, upload_to=users.models.generate_image_path, verbose_name='аватарка'),
        ),
    ]
