# Generated by Django 3.2.16 on 2023-04-02 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напишите название викторины', max_length=50, verbose_name='название викторины')),
                ('status', models.IntegerField(choices=[(1, 'Не начата'), (2, 'Идет'), (3, 'Закончена')], default=1, help_text='Поставьте статус викторины', verbose_name='статус')),
                ('description', models.TextField(help_text='Создайте описание для Вашей викторины', verbose_name='описание')),
                ('start_time', models.DateTimeField(blank=True, help_text='Назначьте стартовое время для Вашей викторины', null=True, verbose_name='стартовое время')),
                ('duration', models.IntegerField(blank=True, help_text='Укажите продолжительность викторины в минутах', null=True, verbose_name='продолжительность')),
            ],
            options={
                'verbose_name': 'викторина',
                'verbose_name_plural': 'викторины',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напишите название вопроса', max_length=100, verbose_name='название вопроса')),
                ('text', models.TextField(help_text='Напишите вопрос', verbose_name='текст')),
                ('quiz', models.ForeignKey(help_text='викторина, к которой относится вопрос', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_question', to='quiz.quiz', verbose_name='викторина')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Напишите вариант ответа', max_length=150, verbose_name='ответ')),
                ('question', models.ForeignKey(help_text='вопрос, к которому относится вариант ответа', on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='quiz.question', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
    ]
