# Generated by Django 3.2.16 on 2023-04-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Variant',
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'вариант ответа', 'verbose_name_plural': 'варианты ответов'},
        ),
    ]
