# Generated by Django 3.2.16 on 2023-04-04 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_auto_20230402_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Опубликован тег или нет', verbose_name='опубликован')),
                ('name', models.CharField(help_text='Введите имя тега', max_length=150, verbose_name='имя тега')),
                ('slug', models.SlugField(help_text='Уникальное для каждого тега поле', max_length=200, unique=True, verbose_name='уникальное поле')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, help_text='сложность вопроса', verbose_name='сложность'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='creator',
            field=models.ForeignKey(help_text='пользователь, который создал викторину', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creator', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='users',
            field=models.ManyToManyField(help_text='Укажите пользователей,которые зарегистрировались на викторину', related_name='quiz_users', to=settings.AUTH_USER_MODEL, verbose_name='пользователи зарегистрированные на викторину'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(help_text='правильный ответ или нет', verbose_name='правильность ответа')),
                ('question', models.ForeignKey(help_text='вопрос на который пользователь дал ответ', on_delete=django.db.models.deletion.CASCADE, related_name='useranswer_question', to='quiz.question', verbose_name='вопрос')),
                ('user', models.ForeignKey(help_text='пользователь, который дал ответ', on_delete=django.db.models.deletion.CASCADE, related_name='useranswer_user', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'ответ пользователя',
                'verbose_name_plural': 'ответы пользователей',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(help_text='выберите теги вопроса', related_name='question_tags', to='quiz.Tag', verbose_name='теги вопроса'),
        ),
    ]
