# Generated by Django 3.2.16 on 2023-04-04 19:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20230404_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Напишите вопрос', verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Создайте описание для Вашей викторины', verbose_name='описание'),
        ),
    ]
