# Generated by Django 3.2.16 on 2023-04-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20230404_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='time_answered',
            field=models.DateTimeField(auto_now_add=True, help_text='Время, когда пользователь ответил на вопрос', null=True, verbose_name='время'),
        ),
    ]
