# Generated by Django 3.2.16 on 2023-04-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_useranswer_time_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='выберите теги вопроса', null=True, related_name='question_tags', to='quiz.Tag', verbose_name='теги вопроса'),
        ),
    ]
