# Generated by Django 3.2.16 on 2023-04-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='выберите теги вопроса', related_name='question_tags', to='quiz.Tag', verbose_name='теги вопроса'),
        ),
    ]
