# Generated by Django 3.2.16 on 2023-04-07 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0007_alter_question_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='users',
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_rated',
            field=models.BooleanField(default=True, help_text='Изменяется ли рейтинг пользователя после данной викторины', verbose_name='рейтинговая'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='выберите теги вопроса', related_name='questions', to='quiz.Tag', verbose_name='теги вопроса'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='question',
            field=models.ForeignKey(help_text='вопрос, к которому относится вариант ответа', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='quiz.question', verbose_name='вопрос'),
        ),
        migrations.CreateModel(
            name='QuizResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_before', models.PositiveIntegerField(default=0, help_text='Рейтинг пользователя до участия в викторине', verbose_name='рейтинг до')),
                ('rating_after', models.PositiveIntegerField(default=0, help_text='Рейтинг пользователя после участия в викторине', verbose_name='рейтинг после')),
                ('solved', models.PositiveIntegerField(default=0, help_text='Верно решенные задачи', verbose_name='задачи')),
                ('place', models.PositiveIntegerField(default=0, help_text='Место пользователя в викторине', verbose_name='место')),
                ('quiz', models.ForeignKey(help_text='Викторина, к которой относится результат', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quiz.quiz', verbose_name='викторина')),
                ('user', models.ForeignKey(help_text='Пользователь, участвующий в викторине', on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'результат',
                'verbose_name_plural': 'результаты',
            },
        ),
    ]
