# Generated by Django 3.2.16 on 2023-04-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20230407_1657'),
    ]

    operations = [
    ]
