# Generated by Django 3.2.16 on 2023-04-09 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('quiz', '0009_auto_20230409_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='organizated_by',
            field=models.ForeignKey(blank=True, help_text='Организация, подготовившая викторину', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quizzes', to='organization.organization', verbose_name='организация'),
        ),
    ]
