# Generated by Django 3.2.16 on 2023-04-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_variant_is_correct'),
        ('quiz', '0014_alter_quiz_is_private'),
    ]

    operations = [
    ]
