# Generated by Django 3.2.16 on 2023-04-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_quiz_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='правильный вариант или нет', verbose_name='правильность варианта'),
        ),
    ]
