# Generated by Django 3.2.16 on 2023-04-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_variant_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Время начала викторины в формате день.месяц.год', null=True, verbose_name='стартовое время'),
        ),
    ]
