# Generated by Django 3.2.16 on 2023-04-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_merge_20230416_1523'),
        ('quiz', '0016_alter_quiz_start_time'),
    ]

    operations = [
    ]
