# Generated by Django 3.2.16 on 2023-04-17 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0018_alter_variant_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='status',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Время начала викторины в формате день.месяц.год часы:минуты:секунды', null=True, verbose_name='стартовое время'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(help_text='вопрос на который пользователь дал ответ', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question', verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(help_text='пользователь, который дал ответ', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
