# Generated by Django 3.2.16 on 2023-04-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_quiz_is_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Укажите продолжительность викторины в минутах', null=True, verbose_name='продолжительность'),
        ),
    ]
