# Generated by Django 3.2.16 on 2023-04-20 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_alter_quiz_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Укажите продолжительность викторины в минутах', null=True, validators=[django.core.validators.MinValueValidator(10)], verbose_name='продолжительность'),
        ),
    ]
