# Generated by Django 3.2.16 on 2023-04-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_alter_quiz_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Опубликована или нет', verbose_name='опубликована'),
        ),
    ]
