# Generated by Django 3.2.16 on 2023-05-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_alter_quiz_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Выберите время начала викторины', null=True, verbose_name='стартовое время'),
        ),
    ]
