# Generated by Django 3.2.16 on 2023-05-02 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_alter_quiz_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.PositiveIntegerField(default=10, help_text='Укажите продолжительность викторины в минутах', validators=[django.core.validators.MinValueValidator(10)], verbose_name='продолжительность'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Выберите время начала викторины. Часовой пояс - UTC+03:00', null=True, verbose_name='стартовое время'),
        ),
    ]
