# Generated by Django 3.2.16 on 2023-05-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_auto_20230502_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
