# Generated by Django 3.2.16 on 2023-05-26 19:09

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('quiz', '0027_auto_20230526_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='список тегов, разделенных запятой', related_name='questions', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='теги'),
        ),
    ]
