# Generated by Django 3.2.16 on 2023-05-27 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=0, help_text='сложность вопроса', validators=[django.core.validators.MaxValueValidator(10)], verbose_name='сложность'),
        ),
    ]
