# Generated by Django 3.2.16 on 2023-07-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_auto_20230705_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(help_text='Напишите название вопроса', max_length=50, verbose_name='название вопроса'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='text',
            field=models.CharField(help_text='Напишите вариант ответа', max_length=75, verbose_name='ответ'),
        ),
    ]
