# Generated by Django 3.2.16 on 2023-07-05 20:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_auto_20230705_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Напишите вопрос', max_length=1000, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Создайте описание для Вашей викторины', max_length=1000, verbose_name='описание'),
        ),
    ]
